#!/usr/bin/env php
<?php

/* init services */
$services = require(file_exists($file = (__DIR__ . '/src/bootstrap.php')) ? $file : $file . '.dist');

/* run console application */
$console = new \Tidumper\Console\Console();
$console->setServices($services)
        ->run()
        ;
